apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: "2018-12-23T16:45:02Z"
  name: twitter-cass-tweet
  namespace: default
  resourceVersion: "25993977"
  selfLink: /apis/autoscaling/v2beta1/namespaces/default/horizontalpodautoscalers/twitter-cass-tweet
  uid: 18037307-06d2-11e9-94c0-0a58ac1f1fb8
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
#  - resource:
#      name: cpu
#      targetAverageUtilization: 75
#    type: Resource
  - type: Object
    object:
      target:
        kind: Service
        name: twitter-cass-tweet
      metricName: average-response-time
      targetValue: 300m
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: twitter-cass-tweet

