---
apiVersion: v1
kind: Service
metadata:
  name: locust-master-hpa
  labels:
    name: locust-hpa
    role: master-hpa
spec:
  type: LoadBalancer
  ports:
  - name: loc-master-web
    port: 8089
    protocol: TCP
  - name: loc-master-p1
    port: 5557
    protocol: TCP
  - name: loc-master-p2
    port: 5558
    protocol: TCP
  selector:
    name: locust-hpa
    role: master-hpa
