---
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  type: LoadBalancer
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
    - port: 5557
      targetPort: 5557
      protocol: TCP
    - port: 5558
      targetPort: 5558
      protocol: TCP
  selector:
    name: locust
    role: master

