---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
        - name: locust-master
          image: "maxwang/locust:dev"
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              # Replace the IP with the twitter app IP
              # e.g., value: "http://35.237.107.176:8699"
              value: "http://a94f45c771b3511e9a4640e8e22e09e6-837229101.us-east-1.elb.amazonaws.com"
            - name: ENABLE_TIME_SLOT_PROBABILITY
              value: "1"
            - name: TIME_SLOT_PROBABILITY
              value: "0.1"
            - name: TIME_SLOT_PROBABILITY_STEP_IN_MIN
              value: "30"
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
        - name: locust-worker
          image: "maxwang/locust:dev"
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              # Replace the IP with the twitter app IP
              # e.g., value: "http://35.237.107.176:8699"
              # value: "http://40.76.50.131"
              value: "http://a94f45c771b3511e9a4640e8e22e09e6-837229101.us-east-1.elb.amazonaws.com"
            - name: ENABLE_TIME_SLOT_PROBABILITY
              value: "1"
            - name: TIME_SLOT_PROBABILITY
              value: "0.1"
            - name: TIME_SLOT_PROBABILITY_STEP_IN_MIN
              value: "30"
