---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-master-hpa
  labels:
    name: locust-hpa
    role: master-hpa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: locust-hpa
        role: master-hpa
    spec:
      containers:
        - name: locust-master-hpa
          image: "maxwang/locust:dev"
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              # Replace the IP with the twitter app IP
              value: "http://aadf62738468711e985be06c917d7379-1296932015.us-west-2.elb.amazonaws.com"
            - name: ENABLE_TIME_SLOT_PROBABILITY
              value: "1"
            - name: TIME_SLOT_PROBABILITY
              value: "1.0,0.7,0.4,0.1,0.4,0.7"
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-worker-hpa
  labels:
    name: locust-hpa
    role: worker-hpa
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: locust-hpa
        role: worker-hpa
    spec:
      containers:
        - name: locust-worker-hpa
          image: "maxwang/locust:dev"
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master-hpa
            - name: TARGET_HOST
              # Replace the IP with the twitter app IP
              value: "http://aadf62738468711e985be06c917d7379-1296932015.us-west-2.elb.amazonaws.com"
            - name: ENABLE_TIME_SLOT_PROBABILITY
              value: "1"
            - name: TIME_SLOT_PROBABILITY
              value: "1.0,0.7,0.4,0.1,0.4,0.7"
