{
 "title": "Cassandra Testbed",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Twitter App Service Reponse Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1000*(avg(rate(istio_turbo_service_latency_time_ms_sum{destination_service_name=~\"twitter-cass-.*\",response_code=\"200\"}[10m])/rate(istio_turbo_service_latency_time_ms_count{response_code=\"200\"}[10m])) by (destination_uid))",
     "legendFormat": "{{destination_uid}}"
    }
   ]
  },
  {
   "title": "Twitter App Horizontal Pod Autoscale",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-api-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-api"
    },
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-friend-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-friend"
    },
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-tweet-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-tweet"
    },
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-user-.*\"}[1m])) by (pod_name))",
     "legendFormat": "twitter-cass-user"
    }
   ]
  },
  {
   "title": "Node CPU utlization",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{id=\"/\"}[1m]))by (kubernetes_io_hostname) *50"
    }
   ]
  },
  {
   "title": "Breakdown of average CPU utilization of twitter-cass-tweet pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-tweet-.*\", container_name=\"twitter-cass-tweet\"}[1m]))",
     "legendFormat": "twitter-cass-tweet"
    },
    {
     "expr": "avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-tweet-.*\", container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio-proxy"
    }
   ]
  },
  {
   "title": "Breakdown of average CPU utilization of twitter-cass-api pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-api-.*\", container_name=\"twitter-cass-api\"}[1m]))",
     "legendFormat": "twitter-cass-api"
    },
    {
     "expr": "avg (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"twitter-cass-api-.*\", container_name=\"istio-proxy\"}[1m]))",
     "legendFormat": "istio_proxy"
    }
   ]
  },
  {
   "title": "Twitter App Service QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(istio_turbo_service_request_count{destination_uid=~\"twitter-cass-api.*\", response_code=\"200\"}[3m])) + avg(rate(istio_turbo_service_request_count{destination_uid=~\"twitter-cass-api.*\", response_code=\"302\"}[3m]))",
     "legendFormat": "twitter-cass-api"
    },
    {
     "expr": "avg(rate(istio_turbo_service_request_count{destination_uid=~\"twitter-cass-friend.*\", response_code=\"200\"}[3m]))",
     "legendFormat": "twitter-cass-friend"
    },
    {
     "expr": "avg(rate(istio_turbo_service_request_count{destination_uid=~\"twitter-cass-tweet.*\", response_code=\"200\"}[3m]))",
     "legendFormat": "twitter-cass-tweet"
    },
    {
     "expr": "avg(rate(istio_turbo_service_request_count{destination_uid=~\"twitter-cass-user.*\", response_code=\"200\"}[3m]))",
     "legendFormat": "twitter-cass-user"
    }
   ]
  },
  {
   "title": "Istio Horizontal Pod Autoscale",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"istio-ingressgateway-.*\"}[1m])) by (pod_name))",
     "legendFormat": "istio-ingressgateway"
    },
    {
     "expr": "count(sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod_name=~\"istio-telemetry-.*\"}[1m])) by (pod_name))",
     "legendFormat": "istio-telemetry"
    }
   ]
  },
  {
   "title": "Cassandra Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:(write|read)latency:(50thpercentile|99thpercentile|max)\"})",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cassandra QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_stats{name=~\"org:apache:cassandra:metrics:table:(write|read)latency:oneminuterate\"}",
     "legendFormat": "{{instance}}-{{name}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, 99p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:99thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, 99p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:99thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, 50p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:50thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, 50p (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:50thpercentile\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Read Latency, max (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:readlatency:max\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cassandra Write Latency, max (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "0.001*(cassandra_stats{name=~\"org:apache:cassandra:metrics:table:writelatency:max\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}